import { Network } from "../types/network";

export const NETWORKS: Record<string, Network> = {
  ETHEREUM_MAINNET: {
    name: "Ethereum",
    icon: "https://raw.githubusercontent.com/ethereum/ethereum-org-website/dev/src/assets/eth-logo.svg",
    explorer: "https://etherscan.io",
    color: "from-blue-500 to-purple-500",
    chainId: 1,
    isTestnet: false,
    isActive: false,
  },
  SEPOLIA: {
    name: "Sepolia",
    icon: "https://raw.githubusercontent.com/ethereum/ethereum-org-website/dev/src/assets/eth-logo.svg",
    explorer: "https://sepolia.etherscan.io",
    color: "from-blue-500 to-purple-500",
    chainId: 11155111,
    isTestnet: true,
    isActive: true,
  },
  BASE: {
    name: "Base",
    icon: "https://raw.githubusercontent.com/ethereum/ethereum-org-website/dev/src/assets/base-logo.svg",
    explorer: "https://basescan.org",
    color: "from-blue-400 to-cyan-400",
    chainId: 8453,
    isTestnet: false,
    isActive: false,
  },
  BITKUB: {
    name: "Bitkub Chain",
    icon: "https://assets.coingecko.com/coins/images/25014/small/bitkub.png",
    explorer: "https://bkcscan.com",
    color: "from-green-400 to-emerald-400",
    chainId: 96,
    isTestnet: false,
    isActive: false,
  },
  SCROLL: {
    name: "Scroll",
    icon: "https://assets.coingecko.com/coins/images/30006/small/scroll.png",
    explorer: "https://scrollscan.com",
    color: "from-pink-500 to-rose-500",
    chainId: 534352,
    isTestnet: false,
    isActive: false,
  },
  BASE_SEPOLIA: {
    name: "Base Sepolia",
    icon: "https://raw.githubusercontent.com/ethereum/ethereum-org-website/dev/src/assets/base-logo.svg",
    explorer: "https://sepolia.basescan.org",
    color: "from-blue-400 to-cyan-400",
    chainId: 84532,
    isTestnet: true,
    isActive: true,
  },
  ARBITRUM: {
    name: "Arbitrum",
    icon: "https://assets.coingecko.com/coins/images/16547/small/photo_2023-03-29_21.47.00.jpeg",
    explorer: "https://arbiscan.io",
    color: "from-blue-600 to-indigo-600",
    chainId: 42161,
    isTestnet: false,
    isActive: false,
  },
  OPTIMISM: {
    name: "Optimism",
    icon: "https://assets.coingecko.com/coins/images/25244/small/Optimism.png",
    explorer: "https://optimistic.etherscan.io",
    color: "from-red-500 to-red-600",
    chainId: 10,
    isTestnet: false,
    isActive: false,
  },
  POLYGON: {
    name: "Polygon",
    icon: "https://assets.coingecko.com/coins/images/4713/small/matic-token-icon.png",
    explorer: "https://polygonscan.com",
    color: "from-purple-600 to-indigo-600",
    chainId: 137,
    isTestnet: false,
    isActive: false,
  },
  AVALANCHE: {
    name: "Avalanche",
    icon: "https://assets.coingecko.com/coins/images/12559/small/Avalanche_Circle_RedWhite_Trans.png",
    explorer: "https://snowtrace.io",
    color: "from-red-500 to-red-600",
    chainId: 43114,
    isTestnet: false,
    isActive: false,
  },
  FANTOM: {
    name: "Fantom",
    icon: "https://assets.coingecko.com/coins/images/4001/small/Fantom_round.png",
    explorer: "https://ftmscan.com",
    color: "from-blue-500 to-indigo-500",
    chainId: 250,
    isTestnet: false,
    isActive: false,
  },
  GNOSIS: {
    name: "Gnosis",
    icon: "https://assets.coingecko.com/coins/images/11062/small/Identity-Primary-DarkBG.png",
    explorer: "https://gnosisscan.io",
    color: "from-green-500 to-emerald-500",
    chainId: 100,
    isTestnet: false,
    isActive: false,
  },
  CELO: {
    name: "Celo",
    icon: "https://assets.coingecko.com/coins/images/11090/small/InjXBNx9_400x400.jpg",
    explorer: "https://celoscan.io",
    color: "from-green-400 to-emerald-500",
    chainId: 42220,
    isTestnet: false,
    isActive: false,
  },
  LINEA: {
    name: "Linea",
    icon: "https://assets.coingecko.com/coins/images/33752/small/linea.png",
    explorer: "https://lineascan.build",
    color: "from-green-500 to-teal-500",
    chainId: 59144,
    isTestnet: false,
    isActive: false,
  },
} as const;
